/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package birdpoint.telas;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriano
 */
public class TelaAguardando extends javax.swing.JFrame {

    Integer contador = 0;
    /**
     * Creates new form TelaAguardando
     */
    
    Thread telaCarregando = new Thread(() -> { 
        funcaoContador();
    });
    public TelaAguardando() {
        initComponents();
        telaCarregando.start();
    }
    
    public void funcaoContador(){
        try{
        while(contador<=30){
        tfContador.setText("( "+contador+" )");
        contador++;
        sleep(1000);
        }
        if(contador>30){
            JOptionPane.showMessageDialog(null, "Não foi possível se conectar ao servidor!");
            System.exit(0);
        }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfContador = new javax.swing.JLabel();
        tfImagem = new javax.swing.JLabel();
        tfTipoUsuario1 = new javax.swing.JLabel();
        jlPesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 210));
        setMinimumSize(new java.awt.Dimension(430, 210));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(430, 210));
        getContentPane().setLayout(null);

        tfContador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfContador.setText("()");
        getContentPane().add(tfContador);
        tfContador.setBounds(190, 60, 80, 30);

        tfImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/loading_bigMenor.gif"))); // NOI18N
        getContentPane().add(tfImagem);
        tfImagem.setBounds(180, 100, 50, 60);

        tfTipoUsuario1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfTipoUsuario1.setText("Carregando dados, Aguarde!");
        getContentPane().add(tfTipoUsuario1);
        tfTipoUsuario1.setBounds(80, 30, 300, 30);

        jlPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar_1.png"))); // NOI18N
        jlPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jlPesquisar);
        jlPesquisar.setBounds(-20, 0, 470, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAguardando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAguardando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAguardando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAguardando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAguardando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlPesquisar;
    private javax.swing.JLabel tfContador;
    private javax.swing.JLabel tfImagem;
    private javax.swing.JLabel tfTipoUsuario1;
    // End of variables declaration//GEN-END:variables
}
